/**
 * The game catalogue.
 *
 * Every entry is data: an engine name, a content configuration, the functional
 * domains it trains, the life skill it transfers to, and which difficulty
 * dimensions the adaptive engine may move. No entry contains game logic — that
 * is the point of the engine split, and it is what makes a catalogue this size
 * maintainable and what would let a therapist author a new activity without
 * touching code.
 *
 * `domains` is not decoration. It decides which capability estimates a round
 * feeds, what the therapist dashboard aggregates, and how the hub groups games.
 * If a game's domains are wrong, the analytics are wrong.
 */
import { ENGINES } from '../engines/registry'
import {
  askByAttribute, askByReading, askByListening, askMissing, askVanishing,
  askPhonics, askBeginningSound, askQuantityMatch, askComparison, askCategory,
  askSafety, askHazardKind, askSpatial, askScenario, askByAttrValue, askWhichBin,
  askWhatsMissing, askTimeOfDay, askWordPicture, askMoney, askWhichHand,
} from '../engines/asks'
import { LIFE_SKILL_LABELS } from './groups'
import {
  FaBullseye, FaHashtag, FaArrowsAltH, FaHandPaper, FaRulerHorizontal, FaCircle,
  FaShapes, FaBookOpen, FaSearch, FaBalanceScale, FaArrowUp, FaSyncAlt,
  FaShieldAlt, FaHourglassHalf, FaWater, FaGhost, FaMusic, FaPalette,
  FaPuzzlePiece, FaFont, FaShoppingCart, FaVolumeUp, FaSpellCheck, FaImage,
  FaSignature, FaSortNumericUp, FaMoneyBillWave, FaAlignLeft, FaDrum, FaRoad,
  FaStar, FaPen, FaTooth, FaTshirt, FaSun, FaSnowflake, FaBroom, FaFire,
  FaExclamationTriangle, FaWalking, FaCalendarDay, FaListOl, FaSmile,
  FaQuestion, FaHandsHelping, FaClock, FaCoins,
} from 'react-icons/fa'
import {
  FaHands, FaCow, FaDog, FaTrafficLight, FaChildren, FaGaugeHigh, FaEarListen,
  FaAppleWhole, FaCat, FaGlassWater, FaListCheck, FaFireExtinguisher, FaHand,
  FaSoap,
} from 'react-icons/fa6'
import { GiBalloons, GiSchoolBag, GiMirrorMirror, GiBubbles, GiMaze, GiWashingMachine } from 'react-icons/gi'

// ── adaptive dimension presets ───────────────────────────────────────────────
// One dimension at a time is what the staircase moves; the ORDER here is the
// rotation, so it also encodes what to make harder first.
const DIMS = {
  discriminate: ['targetSize', 'choices', 'distractors', 'eccentricity', 'window'],
  memory: ['memorySpan', 'showMs', 'choices', 'distractors'],
  sequence: ['memorySpan', 'targetSize', 'eccentricity'],
  motor: ['targetSize', 'eccentricity', 'window'],
  inhibit: ['noGoRate', 'window', 'targetSize'],
  flexible: ['noGoRate', 'window', 'targetSize', 'ruleSwitch'],
  trace: ['tolerance', 'steps', 'eccentricity'],
  posture: ['holdMs', 'choices'],
  instruct: ['steps', 'choices', 'targetSize'],
  cue: ['holdMs', 'eccentricity'],
  wait: ['window', 'targetSize', 'eccentricity'],
  bilateral: ['targetSize', 'eccentricity'],
  rhythm: ['pace', 'targetSize', 'eccentricity'],
  collect: ['memorySpan', 'choices', 'targetSize', 'distractors'],
}

/** Builds a catalogue entry, filling in everything derivable. */
function g(entry) {
  return {
    usesReach: true,
    lifeSkillLabel: entry.lifeSkill ? LIFE_SKILL_LABELS[entry.lifeSkill] : null,
    adaptive: { dimensions: DIMS[entry.dims] || DIMS.discriminate, start: entry.start || {} },
    // Resolved lazily so an unknown engine name fails loudly at play time with
    // the game id in hand, rather than silently at module load.
    create: (self) => ENGINES[entry.engine](self),
    ...entry,
  }
}

export const GAMES = [
  // ══════════════════════════════════════════════════════════════════════════
  // BODY & REACH
  // ══════════════════════════════════════════════════════════════════════════
  g({
    id: 'setup-space',
    group: 'body',
    title: 'Set Up My Space',
    icon: FaBullseye,
    color: 'teal',
    how: 'Five easy stretches so every game lands exactly where you can reach. Do this once, first.',
    engine: 'calibration',
    dims: 'motor',
    domains: ['reachAccuracy', 'motorPlanning'],
    lifeSkill: 'bodyAwareness',
    featured: true,
    usesReach: false,
    // A measurement, not a challenge. Five levels of "hold your arm out" would
    // be five levels of nothing, and locking the calibration behind a level
    // would lock every other game's reach envelope behind it too.
    journey: false,
    config: {},
  }),
  g({
    id: 'ball-pop',
    group: 'body',
    title: 'Ball Pop',
    icon: GiBalloons,
    color: 'pink',
    how: 'Balloons appear in your reach — pop each one before it floats away.',
    engine: 'pop',
    dims: 'motor',
    domains: ['reactionSpeed', 'reachAccuracy', 'visualDiscrimination'],
    lifeSkill: 'bodyAwareness',
    featured: true,
    config: {
      spawns: 16,
      concurrent: 1,
      lifetimeMs: 3200,
      sets: ['shapes'],
      spriteKind: 'shape',
    },
  }),
  g({
    id: 'number-hunt',
    group: 'body',
    title: 'Whole-Body Number Hunt',
    icon: FaHashtag,
    color: 'orange',
    how: 'Numbers appear high, low, left and right. Use your whole body to reach them.',
    engine: 'pop',
    dims: 'motor',
    domains: ['reachAccuracy', 'motorPlanning', 'readingSymbol'],
    lifeSkill: 'bodyAwareness',
    start: { eccentricity: 2 },
    config: {
      spawns: 14,
      concurrent: 1,
      lifetimeMs: 4200,
      sets: ['digits'],
      spriteKind: 'text',
      wholeBody: true,
    },
  }),
  g({
    id: 'two-hand-catch',
    group: 'body',
    title: 'Two-Hand Catch',
    icon: FaHands,
    color: 'blue',
    how: 'Two shapes, one for each hand. Touch them both at the same moment.',
    engine: 'bilateral',
    dims: 'bilateral',
    domains: ['bilateralCoordination', 'motorPlanning', 'reachAccuracy'],
    lifeSkill: 'bodyAwareness',
    featured: true,
    config: { trials: 10, mode: 'together', sets: ['shapes'], spriteKind: 'shape' },
  }),
  g({
    id: 'cross-the-middle',
    group: 'body',
    title: 'Cross the Middle',
    icon: FaArrowsAltH,
    color: 'purple',
    how: 'Your left hand fetches things on the right, and the other way round.',
    engine: 'bilateral',
    dims: 'bilateral',
    domains: ['motorPlanning', 'bilateralCoordination', 'spatialConcepts'],
    lifeSkill: 'dressing',
    config: { trials: 10, mode: 'cross', sets: ['shapes', 'colors'], spriteKind: 'shape' },
  }),
  g({
    id: 'left-or-right',
    group: 'body',
    title: 'Left or Right?',
    icon: FaHandPaper,
    color: 'yellow',
    how: '"Touch it with your LEFT hand." Knowing which is which.',
    engine: 'tap',
    dims: 'motor',
    domains: ['spatialConcepts', 'motorPlanning', 'auditoryComprehension'],
    lifeSkill: 'bodyAwareness',
    config: {
      trials: 10,
      layout: 'row',
      spriteKind: 'shape',
      makeTrial: askWhichHand({ sets: ['shapes'] }),
    },
  }),
  g({
    id: 'reach-near-far',
    group: 'body',
    title: 'Reach Near & Far',
    icon: FaRulerHorizontal,
    color: 'green',
    how: 'Some things are close, some are right at the edge of your reach.',
    engine: 'pop',
    dims: 'motor',
    domains: ['reachAccuracy', 'motorPlanning'],
    lifeSkill: 'bodyAwareness',
    start: { eccentricity: 1 },
    config: {
      spawns: 14,
      concurrent: 1,
      lifetimeMs: 4500,
      sets: ['colors'],
      spriteKind: 'shape',
    },
  }),

  // ══════════════════════════════════════════════════════════════════════════
  // LOOK & FIND
  // ══════════════════════════════════════════════════════════════════════════
  g({
    id: 'find-touch-colour',
    group: 'look',
    title: 'Find & Touch',
    icon: FaCircle,
    color: 'blue',
    how: '"Touch the blue one." Colours first, then shapes and numbers.',
    engine: 'tap',
    dims: 'discriminate',
    domains: ['visualDiscrimination', 'auditoryComprehension', 'reachAccuracy'],
    lifeSkill: 'instructions',
    featured: true,
    config: {
      trials: 12,
      spriteKind: 'shape',
      makeTrial: askByAttribute({ sets: ['colors'], attribute: 'color', spriteKind: 'shape', noun: 'one' }),
    },
  }),
  g({
    id: 'find-shape',
    group: 'look',
    title: 'Find the Shape',
    icon: FaShapes,
    color: 'orange',
    how: '"Touch the triangle." Ten shapes, some easy to mix up.',
    engine: 'tap',
    dims: 'discriminate',
    domains: ['visualDiscrimination', 'auditoryComprehension'],
    lifeSkill: 'instructions',
    config: {
      trials: 12,
      spriteKind: 'shape',
      makeTrial: askByAttribute({ sets: ['shapes'], attribute: 'shape', spriteKind: 'shape', noun: 'shape' }),
    },
  }),
  g({
    id: 'read-and-find',
    group: 'look',
    title: 'Read & Find',
    icon: FaBookOpen,
    color: 'purple',
    how: 'The word CIRCLE appears. Touch the circle. Nothing is read aloud.',
    engine: 'tap',
    dims: 'discriminate',
    domains: ['readingSymbol', 'visualDiscrimination'],
    lifeSkill: 'literacy',
    config: {
      trials: 10,
      spriteKind: 'shape',
      makeTrial: askByReading({ sets: ['shapes', 'colors'], spriteKind: 'shape' }),
    },
  }),
  g({
    id: 'listen-and-find',
    group: 'look',
    title: 'Listen & Find',
    icon: FaEarListen,
    color: 'teal',
    how: 'A voice says the word. Nothing is written. Find what you hear.',
    engine: 'tap',
    dims: 'discriminate',
    domains: ['auditoryComprehension', 'visualDiscrimination'],
    lifeSkill: 'instructions',
    featured: true,
    config: {
      trials: 12,
      captions: false,
      makeTrial: askByListening({ sets: ['animals', 'food'], spriteKind: 'emoji' }),
    },
  }),
  g({
    id: 'search-the-room',
    group: 'look',
    title: 'Search the Room',
    icon: FaSearch,
    color: 'yellow',
    how: 'One right answer hiding among lots of very similar ones.',
    engine: 'tap',
    dims: 'discriminate',
    domains: ['visualDiscrimination', 'sustainedAttention'],
    lifeSkill: 'independence',
    start: { choices: 4, distractors: 3 },
    config: {
      trials: 10,
      captions: false,
      makeTrial: askByListening({ sets: ['school', 'household', 'kitchen'], spriteKind: 'emoji' }),
    },
  }),
  g({
    id: 'big-or-small',
    group: 'look',
    title: 'Big or Small?',
    icon: FaBalanceScale,
    color: 'green',
    how: 'Bigger, smaller, more, fewer — the comparison words.',
    engine: 'tap',
    dims: 'discriminate',
    domains: ['visualDiscrimination', 'spatialConcepts', 'auditoryComprehension'],
    lifeSkill: 'numeracy',
    config: { trials: 10, layout: 'row', makeTrial: askComparison() },
  }),
  g({
    id: 'above-or-below',
    group: 'look',
    title: 'Above or Below?',
    icon: FaArrowUp,
    color: 'pink',
    how: '"Touch the cat above the box." Space words, in space.',
    engine: 'tap',
    dims: 'discriminate',
    domains: ['spatialConcepts', 'auditoryComprehension', 'visualDiscrimination'],
    lifeSkill: 'navigation',
    config: { trials: 10, makeTrial: askSpatial() },
  }),
  g({
    id: 'which-animal',
    group: 'look',
    title: 'Which Group?',
    icon: FaCow,
    color: 'blue',
    how: '"Touch the farm animal." Sorting the world into kinds.',
    engine: 'tap',
    dims: 'discriminate',
    domains: ['visualDiscrimination', 'auditoryComprehension'],
    lifeSkill: 'instructions',
    config: {
      trials: 10,
      captions: true,
      makeTrial: askCategory({ sets: ['animals', 'vehicles'], by: 'cat', label: (v) => `the ${v}` }),
    },
  }),

  // ══════════════════════════════════════════════════════════════════════════
  // STOP & THINK
  // ══════════════════════════════════════════════════════════════════════════
  g({
    id: 'go-no-go-animals',
    group: 'stop',
    title: 'Pets Only!',
    icon: FaDog,
    color: 'green',
    how: 'Touch the pets. Leave the wild animals completely alone.',
    engine: 'goNoGo',
    dims: 'inhibit',
    domains: ['inhibition', 'sustainedAttention', 'visualDiscrimination'],
    lifeSkill: 'selfRegulation',
    featured: true,
    config: {
      trials: 20,
      goSets: ['animals'],
      noGoSets: ['animals'],
      goCats: ['pet', 'farm'],
      goLabel: 'pets and farm animals',
      noGoLabel: 'wild animals',
    },
  }),
  g({
    id: 'rule-switch',
    group: 'stop',
    title: 'Rule Switch',
    icon: FaSyncAlt,
    color: 'purple',
    how: 'Touch the animals… then suddenly the rule changes to vehicles.',
    engine: 'goNoGo',
    dims: 'flexible',
    domains: ['cognitiveFlexibility', 'inhibition', 'sustainedAttention'],
    lifeSkill: 'selfRegulation',
    featured: true,
    config: {
      trials: 22,
      goSets: ['animals', 'vehicles'],
      noGoSets: ['animals', 'vehicles'],
      goCats: ['animal'],
      goLabel: 'animals',
      noGoLabel: 'vehicles',
      ruleSwitch: true,
    },
  }),
  g({
    id: 'safe-or-not',
    group: 'stop',
    title: 'Safe Hands',
    icon: FaShieldAlt,
    color: 'red',
    how: 'Touch what is safe to hold. Never touch what is not.',
    engine: 'goNoGo',
    dims: 'inhibit',
    domains: ['inhibition', 'visualDiscrimination'],
    lifeSkill: 'homeSafety',
    config: {
      trials: 18,
      goSets: ['safety'],
      noGoSets: ['safety'],
      goTest: (i) => i.attrs?.safety === 'safe',
      goLabel: 'safe things',
      noGoLabel: 'unsafe things',
    },
  }),
  g({
    id: 'red-light-green-light',
    group: 'stop',
    title: 'Red Light, Green Light',
    icon: FaTrafficLight,
    color: 'red',
    how: 'Move when it is green. Freeze completely when it turns red.',
    engine: 'cue',
    dims: 'cue',
    domains: ['inhibition', 'sustainedAttention', 'motorPlanning'],
    lifeSkill: 'selfRegulation',
    featured: true,
    showBody: true,
    config: { trials: 8, mode: 'lights', amber: false },
  }),
  g({
    id: 'traffic-light-body',
    group: 'stop',
    title: 'Traffic Light Game',
    icon: FaChildren,
    color: 'orange',
    how: 'Green walk, amber get ready, red freeze — like a real crossing.',
    engine: 'cue',
    dims: 'cue',
    domains: ['inhibition', 'cognitiveFlexibility', 'sustainedAttention'],
    lifeSkill: 'roadSafety',
    showBody: true,
    config: { trials: 8, mode: 'lights', amber: true },
  }),
  g({
    id: 'wait-for-it',
    group: 'stop',
    title: 'Wait For It',
    icon: FaHourglassHalf,
    color: 'yellow',
    how: 'The star is there — but do not touch it until it turns green.',
    engine: 'cue',
    dims: 'wait',
    domains: ['inhibition', 'sustainedAttention'],
    lifeSkill: 'selfRegulation',
    config: { trials: 12, mode: 'wait', sets: ['shapes'] },
  }),
  g({
    id: 'calm-movement',
    group: 'stop',
    title: 'Calm Movement',
    icon: FaWater,
    color: 'teal',
    how: 'Keep moving, but keep it gentle. Not too still, not too wild.',
    engine: 'cue',
    dims: 'cue',
    domains: ['motorPlanning', 'sustainedAttention'],
    lifeSkill: 'selfRegulation',
    showBody: true,
    config: { trials: 6, mode: 'calm' },
  }),
  g({
    id: 'fast-vs-slow',
    group: 'stop',
    title: 'Fast or Slow',
    icon: FaGaugeHigh,
    color: 'blue',
    how: 'Move your arms fast, then very slowly. Choosing your own speed.',
    engine: 'pose',
    dims: 'posture',
    domains: ['motorPlanning', 'inhibition'],
    lifeSkill: 'selfRegulation',
    showBody: true,
    config: { trials: 8, mode: 'speed' },
  }),

  // ══════════════════════════════════════════════════════════════════════════
  // REMEMBER
  // ══════════════════════════════════════════════════════════════════════════
  g({
    id: 'vanishing-target',
    group: 'remember',
    title: 'Vanishing Target',
    icon: FaGhost,
    color: 'purple',
    how: 'A letter flashes up, then disappears. Which one was it?',
    engine: 'tap',
    dims: 'memory',
    domains: ['workingMemory', 'visualDiscrimination'],
    lifeSkill: 'instructions',
    featured: true,
    config: {
      trials: 10,
      spriteKind: 'text',
      makeTrial: askVanishing({ sets: ['lettersUpper'], spriteKind: 'text' }),
    },
  }),
  g({
    id: 'simon-reach',
    group: 'remember',
    title: 'Simon Reach',
    icon: FaMusic,
    color: 'pink',
    how: 'Watch the order the shapes light up in, then copy it exactly.',
    engine: 'sequence',
    dims: 'sequence',
    domains: ['workingMemory', 'sequencing', 'reachAccuracy'],
    lifeSkill: 'instructions',
    featured: true,
    config: { trials: 6, mode: 'demo', layout: 'row', sets: ['shapes'] },
  }),
  g({
    id: 'copy-the-pattern',
    group: 'remember',
    title: 'Copy the Pattern',
    icon: FaPalette,
    color: 'orange',
    how: 'Red, blue, yellow, red — watch the colour pattern, then repeat it.',
    engine: 'sequence',
    dims: 'sequence',
    domains: ['workingMemory', 'sequencing', 'visualDiscrimination'],
    lifeSkill: 'literacy',
    config: { trials: 6, mode: 'demo', layout: 'row', sets: ['colors'] },
  }),
  g({
    id: 'repair-the-sequence',
    group: 'remember',
    title: 'Repair the Sequence',
    icon: FaPuzzlePiece,
    color: 'blue',
    how: '1, 2, ?, 4 — which one is missing?',
    engine: 'tap',
    dims: 'memory',
    domains: ['sequencing', 'workingMemory', 'readingSymbol'],
    lifeSkill: 'numeracy',
    config: { trials: 10, makeTrial: askMissing({ kind: 'digits' }) },
  }),
  g({
    id: 'repair-the-alphabet',
    group: 'remember',
    title: 'Repair the Alphabet',
    icon: FaFont,
    color: 'green',
    how: 'A, B, ?, D — find the letter that fell out.',
    engine: 'tap',
    dims: 'memory',
    domains: ['sequencing', 'workingMemory', 'readingSymbol'],
    lifeSkill: 'literacy',
    config: { trials: 10, makeTrial: askMissing({ kind: 'lettersUpper' }) },
  }),
  g({
    id: 'whats-missing',
    group: 'remember',
    title: "What's Missing?",
    icon: GiSchoolBag,
    color: 'yellow',
    how: 'Look in the school bag, then say what went missing.',
    engine: 'tap',
    dims: 'memory',
    domains: ['workingMemory', 'visualDiscrimination'],
    lifeSkill: 'school',
    config: { trials: 8, captions: true, makeTrial: askWhatsMissing({ sets: ['school'] }) },
  }),
  g({
    id: 'grocery-mission',
    group: 'remember',
    title: 'Grocery Mission',
    icon: FaShoppingCart,
    color: 'teal',
    how: '"Get milk, an apple and bread." Hold the list in your head and fetch them.',
    engine: 'collect',
    dims: 'collect',
    domains: ['workingMemory', 'sequencing', 'independence'],
    lifeSkill: 'shopping',
    featured: true,
    config: { trials: 5, task: 'list', mode: 'touch', sets: ['food'] },
  }),

  // ══════════════════════════════════════════════════════════════════════════
  // LETTERS & NUMBERS
  // ══════════════════════════════════════════════════════════════════════════
  g({
    id: 'phonics-reach',
    group: 'learn',
    title: 'Phonics Reach',
    icon: FaVolumeUp,
    color: 'orange',
    how: 'You hear /b/. Reach for the letter that makes that sound.',
    engine: 'tap',
    dims: 'discriminate',
    domains: ['readingSymbol', 'auditoryComprehension'],
    lifeSkill: 'literacy',
    featured: true,
    config: { trials: 12, spriteKind: 'text', makeTrial: askPhonics() },
  }),
  g({
    id: 'beginning-sound',
    group: 'learn',
    title: 'Beginning Sound',
    icon: FaCat,
    color: 'pink',
    how: '"Which one starts with /k/?" Reach the cat.',
    engine: 'tap',
    dims: 'discriminate',
    domains: ['readingSymbol', 'auditoryComprehension'],
    lifeSkill: 'literacy',
    config: { trials: 10, captions: true, makeTrial: askBeginningSound({ sets: ['words'] }) },
  }),
  g({
    id: 'word-builder',
    group: 'learn',
    title: 'Word Builder',
    icon: FaSpellCheck,
    color: 'purple',
    how: 'Spell C-A-T by reaching the letters in order.',
    engine: 'sequence',
    dims: 'sequence',
    domains: ['readingSymbol', 'sequencing', 'workingMemory'],
    lifeSkill: 'literacy',
    featured: true,
    config: { trials: 6, mode: 'spell', layout: 'row' },
  }),
  g({
    id: 'word-and-picture',
    group: 'learn',
    title: 'Word & Picture',
    icon: FaImage,
    color: 'blue',
    how: 'The word SUN appears. Touch the picture that matches.',
    engine: 'tap',
    dims: 'discriminate',
    domains: ['readingSymbol', 'visualDiscrimination'],
    lifeSkill: 'literacy',
    config: { trials: 10, makeTrial: askWordPicture({ direction: 'wordToPicture' }) },
  }),
  g({
    id: 'air-writing',
    group: 'learn',
    title: 'Air Writing',
    icon: FaSignature,
    color: 'teal',
    how: 'Write letters and numbers in the air with your finger.',
    engine: 'trace',
    dims: 'trace',
    domains: ['motorPlanning', 'readingSymbol', 'reachAccuracy'],
    lifeSkill: 'literacy',
    featured: true,
    config: { trials: 5, mode: 'glyph', penDown: false },
  }),
  g({
    id: 'number-match',
    group: 'learn',
    title: 'How Many?',
    icon: FaSortNumericUp,
    color: 'green',
    how: 'The number 5 appears. Touch the group with five things in it.',
    engine: 'tap',
    dims: 'discriminate',
    domains: ['readingSymbol', 'visualDiscrimination'],
    lifeSkill: 'numeracy',
    config: { trials: 10, makeTrial: askQuantityMatch({ direction: 'numeralToDots' }) },
  }),
  g({
    id: 'count-and-collect',
    group: 'learn',
    title: 'Count & Collect',
    icon: FaAppleWhole,
    color: 'red',
    how: '"Collect four apples." Counting while you move.',
    engine: 'collect',
    dims: 'collect',
    domains: ['workingMemory', 'reachAccuracy', 'sustainedAttention'],
    lifeSkill: 'numeracy',
    featured: true,
    config: { trials: 6, task: 'count', mode: 'touch', sets: ['food'] },
  }),
  g({
    id: 'money-shop',
    group: 'learn',
    title: 'Money Shop',
    icon: FaMoneyBillWave,
    color: 'yellow',
    how: 'The apple costs 30c. Pick the coins that pay for it.',
    engine: 'collect',
    dims: 'collect',
    domains: ['workingMemory', 'sequencing', 'independence'],
    lifeSkill: 'money',
    config: { trials: 5, task: 'money', mode: 'touch', sets: ['money'] },
  }),
  g({
    id: 'sentence-order',
    group: 'learn',
    title: 'Sentence Order',
    icon: FaAlignLeft,
    color: 'blue',
    how: 'I / want / water — put the words in the right order.',
    engine: 'sequence',
    dims: 'sequence',
    domains: ['sequencing', 'readingSymbol', 'workingMemory'],
    lifeSkill: 'communication',
    config: { trials: 6, mode: 'sentence', layout: 'row' },
  }),

  // ══════════════════════════════════════════════════════════════════════════
  // MOVE & COPY
  // ══════════════════════════════════════════════════════════════════════════
  g({
    id: 'rhythm-reach',
    group: 'move',
    title: 'Rhythm Reach',
    icon: FaDrum,
    color: 'pink',
    how: 'Touch the shape exactly on every beat. Perfect, great, close — all count.',
    engine: 'rhythm',
    dims: 'rhythm',
    domains: ['motorPlanning', 'inhibition', 'sustainedAttention'],
    lifeSkill: 'selfRegulation',
    featured: true,
    config: { beats: 24, leadInBeats: 4, moveTargetEvery: 4, sets: ['shapes'] },
  }),
  g({
    id: 'mirror-me',
    group: 'move',
    title: 'Mirror Me',
    icon: GiMirrorMirror,
    color: 'purple',
    how: 'Copy the position the little figure is holding.',
    engine: 'pose',
    dims: 'posture',
    domains: ['motorPlanning', 'bilateralCoordination', 'visualDiscrimination'],
    lifeSkill: 'bodyAwareness',
    featured: true,
    showBody: true,
    config: { trials: 8, mode: 'imitate', holdMs: 900 },
  }),
  g({
    id: 'copy-my-gesture',
    group: 'move',
    title: 'Copy My Gesture',
    icon: FaHand,
    color: 'yellow',
    how: 'Wave, thumbs up, point, open palm — the gestures people use.',
    engine: 'pose',
    dims: 'posture',
    domains: ['motorPlanning', 'socialReasoning'],
    lifeSkill: 'communication',
    showBody: true,
    config: { trials: 8, mode: 'gesture', holdMs: 800 },
  }),
  g({
    id: 'personal-space',
    group: 'move',
    title: 'My Space Bubble',
    icon: GiBubbles,
    color: 'teal',
    how: 'Keep your body inside your bubble — then step right outside it.',
    engine: 'pose',
    dims: 'posture',
    domains: ['spatialConcepts', 'socialReasoning', 'inhibition'],
    lifeSkill: 'socialPlay',
    showBody: true,
    config: { trials: 8, mode: 'bubble', holdMs: 1200 },
  }),
  g({
    id: 'trace-the-road',
    group: 'move',
    title: 'Trace the Road',
    icon: FaRoad,
    color: 'orange',
    how: 'Drive your finger along the winding road without going off it.',
    engine: 'trace',
    dims: 'trace',
    domains: ['motorPlanning', 'reachAccuracy', 'sustainedAttention'],
    lifeSkill: 'literacy',
    featured: true,
    config: { trials: 5, mode: 'road' },
  }),
  g({
    id: 'shape-drawing',
    group: 'move',
    title: 'Shape Drawing',
    icon: FaStar,
    color: 'blue',
    how: 'Draw a circle, a square, a star — in the air.',
    engine: 'trace',
    dims: 'trace',
    domains: ['motorPlanning', 'visualDiscrimination'],
    lifeSkill: 'literacy',
    config: {
      trials: 5,
      mode: 'shape',
      shapes: ['circle', 'square', 'triangle', 'diamond', 'star', 'heart', 'zigzag', 'wave'],
    },
  }),
  g({
    id: 'ar-maze',
    group: 'move',
    title: 'Finger Maze',
    icon: GiMaze,
    color: 'green',
    how: 'Find your way through the maze without touching the walls.',
    engine: 'trace',
    dims: 'trace',
    domains: ['motorPlanning', 'sequencing', 'sustainedAttention'],
    lifeSkill: 'navigation',
    config: { trials: 5, mode: 'maze' },
  }),
  g({
    id: 'pinch-and-write',
    group: 'move',
    title: 'Pinch & Write',
    icon: FaPen,
    color: 'red',
    how: 'Pinch your finger and thumb to hold the pen, then write. Like a real pencil grip.',
    engine: 'trace',
    dims: 'trace',
    domains: ['motorPlanning', 'reachAccuracy', 'readingSymbol'],
    lifeSkill: 'literacy',
    config: { trials: 4, mode: 'glyph', penDown: true, glyphs: ['l', 'i', 't', 'o', 'c', 'a', 's'] },
  }),

  // ══════════════════════════════════════════════════════════════════════════
  // MY DAY
  // ══════════════════════════════════════════════════════════════════════════
  g({
    id: 'handwashing',
    group: 'day',
    title: 'Wash My Hands',
    icon: FaSoap,
    color: 'blue',
    how: 'Tap on, wet, soap, rub, rinse, dry — all in the right order.',
    engine: 'sequence',
    dims: 'sequence',
    domains: ['sequencing', 'independence', 'workingMemory'],
    lifeSkill: 'hygiene',
    featured: true,
    config: { trials: 4, mode: 'routine', layout: 'row', sequenceIds: ['handwashing'] },
  }),
  g({
    id: 'toothbrushing',
    group: 'day',
    title: 'Brush My Teeth',
    icon: FaTooth,
    color: 'teal',
    how: 'Every step of brushing, in order.',
    engine: 'sequence',
    dims: 'sequence',
    domains: ['sequencing', 'independence', 'sustainedAttention'],
    lifeSkill: 'hygiene',
    config: { trials: 4, mode: 'routine', layout: 'row', sequenceIds: ['toothbrushing'] },
  }),
  g({
    id: 'getting-dressed',
    group: 'day',
    title: 'Getting Dressed',
    icon: FaTshirt,
    color: 'purple',
    how: 'Underwear, top, trousers, socks, shoes — order matters.',
    engine: 'sequence',
    dims: 'sequence',
    domains: ['sequencing', 'independence', 'motorPlanning'],
    lifeSkill: 'dressing',
    featured: true,
    config: { trials: 4, mode: 'routine', layout: 'row', sequenceIds: ['gettingDressed'] },
  }),
  g({
    id: 'morning-routine',
    group: 'day',
    title: 'Morning Routine',
    icon: FaSun,
    color: 'orange',
    how: 'Wake up, toilet, wash, dress, breakfast, bag.',
    engine: 'sequence',
    dims: 'sequence',
    domains: ['sequencing', 'independence', 'workingMemory'],
    lifeSkill: 'routines',
    config: { trials: 4, mode: 'routine', layout: 'row', sequenceIds: ['morningRoutine', 'bedtimeRoutine'] },
  }),
  g({
    id: 'pack-my-bag',
    group: 'day',
    title: 'Pack My School Bag',
    icon: GiSchoolBag,
    color: 'green',
    how: 'Take what you need for school. Leave the rest behind.',
    engine: 'collect',
    dims: 'collect',
    domains: ['sequencing', 'workingMemory', 'independence'],
    lifeSkill: 'school',
    featured: true,
    config: {
      trials: 5,
      task: 'need',
      mode: 'touch',
      sets: ['school', 'household', 'hygiene'],
      needCat: 'school',
      needPrompt: 'Pack what you need for school',
    },
  }),
  g({
    id: 'sort-the-groceries',
    group: 'day',
    title: 'Sort the Groceries',
    icon: FaSnowflake,
    color: 'blue',
    how: 'Pinch to pick it up, then drop it in the fridge, freezer or cupboard.',
    engine: 'collect',
    dims: 'collect',
    domains: ['sequencing', 'visualDiscrimination', 'independence'],
    lifeSkill: 'kitchen',
    featured: true,
    config: {
      trials: 5,
      task: 'sort',
      mode: 'drag',
      sets: ['food'],
      sortAttr: 'store',
      sortPrompt: 'Put the shopping away',
    },
  }),
  g({
    id: 'laundry-sort',
    group: 'day',
    title: 'Laundry Sort',
    icon: GiWashingMachine,
    color: 'pink',
    how: 'Lights in one basket, darks in the other.',
    engine: 'collect',
    dims: 'collect',
    domains: ['visualDiscrimination', 'independence'],
    lifeSkill: 'chores',
    config: {
      trials: 5,
      task: 'sort',
      mode: 'drag',
      sets: ['clothing'],
      sortAttr: 'laundry',
      sortPrompt: 'Sort the washing',
    },
  }),
  g({
    id: 'tidy-the-room',
    group: 'day',
    title: 'Tidy the Room',
    icon: FaBroom,
    color: 'yellow',
    how: 'Everything goes back to the room it belongs in.',
    engine: 'collect',
    dims: 'collect',
    domains: ['sequencing', 'independence', 'visualDiscrimination'],
    lifeSkill: 'chores',
    config: {
      trials: 5,
      task: 'sort',
      mode: 'drag',
      sets: ['household', 'kitchen', 'hygiene', 'school'],
      sortAttr: 'room',
      sortPrompt: 'Put everything back where it lives',
    },
  }),
  g({
    id: 'where-does-it-go',
    group: 'day',
    title: 'Where Does It Go?',
    icon: FaGlassWater,
    color: 'teal',
    how: 'Milk — fridge, freezer or cupboard? Touch the right one.',
    engine: 'tap',
    dims: 'discriminate',
    domains: ['visualDiscrimination', 'independence'],
    lifeSkill: 'kitchen',
    config: { trials: 10, makeTrial: askWhichBin({ sets: ['food'], attr: 'store' }) },
  }),
  g({
    id: 'hot-sharp-safe',
    group: 'day',
    title: 'Hot, Sharp or Safe',
    icon: FaFire,
    color: 'red',
    how: 'Which one gets hot? Which one is sharp? Which one is safe?',
    engine: 'tap',
    dims: 'discriminate',
    domains: ['visualDiscrimination', 'inhibition'],
    lifeSkill: 'homeSafety',
    config: { trials: 10, captions: true, makeTrial: askHazardKind() },
  }),
  g({
    id: 'safe-or-unsafe',
    group: 'day',
    title: 'Safe or Not Safe?',
    icon: FaExclamationTriangle,
    color: 'orange',
    how: 'Sometimes touch the safe thing, sometimes point out the dangerous one.',
    engine: 'tap',
    dims: 'discriminate',
    domains: ['visualDiscrimination', 'socialReasoning'],
    lifeSkill: 'homeSafety',
    config: { trials: 10, captions: true, makeTrial: askSafety({ sets: ['safety', 'kitchen'] }) },
  }),
  g({
    id: 'crossing-the-road',
    group: 'day',
    title: 'Crossing the Road',
    icon: FaWalking,
    color: 'green',
    how: 'Stop, look, listen, wait, cross — the order that keeps you safe.',
    engine: 'sequence',
    dims: 'sequence',
    domains: ['sequencing', 'inhibition', 'independence'],
    lifeSkill: 'roadSafety',
    featured: true,
    config: { trials: 4, mode: 'routine', layout: 'row', sequenceIds: ['crossingRoad'] },
  }),
  g({
    id: 'clean-or-dirty',
    group: 'day',
    title: 'Needs Washing?',
    icon: FaSoap,
    color: 'blue',
    // Deliberately "does this get washed?" rather than "is this clean or
    // dirty?": clean and dirty are states a single picture cannot show, so that
    // question would be unanswerable. Whether a thing goes in the wash at all
    // is an inherent property, and it is the same categorisation skill.
    how: 'Socks go in the wash. Books do not. Which one needs washing?',
    engine: 'tap',
    dims: 'discriminate',
    domains: ['visualDiscrimination', 'independence'],
    lifeSkill: 'chores',
    config: {
      trials: 10,
      captions: true,
      makeTrial: askByAttrValue({
        sets: ['clothing', 'kitchen', 'school', 'hygiene', 'household'],
        attr: 'washable',
        phrasing: {
          plain: (v) =>
            v === 'yes' ? 'Touch the one that needs washing.' : 'Touch the one that never gets washed.',
          natural: (v) =>
            v === 'yes'
              ? "It's time to do the washing. What goes in?"
              : 'Which one must stay out of the water?',
        },
      }),
    },
  }),
  g({
    id: 'my-day',
    group: 'day',
    title: 'My Whole Day',
    icon: FaCalendarDay,
    color: 'yellow',
    how: 'Wash, dress, pack, pay, cross the road, listen to the teacher, ask for help. The whole day, in one go.',
    engine: 'mission',
    dims: 'sequence',
    domains: [
      'sequencing', 'workingMemory', 'independence', 'inhibition',
      'auditoryComprehension', 'motorPlanning', 'socialReasoning',
    ],
    lifeSkill: 'independence',
    featured: true,
    big: true,
    config: {
      opening: 'Good morning! Let us get through the day together.',
      openingSay: 'Good morning. Let us get through the day together.',
      chain: [
        {
          id: 'wash',
          title: 'Wash your hands',
          say: 'First, wash your hands.',
          icon: FaSoap,
          engine: 'sequence',
          lifeSkill: 'hygiene',
          domains: ['sequencing', 'independence'],
          config: { trials: 1, mode: 'routine', layout: 'row', sequenceIds: ['handwashing'] },
        },
        {
          id: 'dress',
          title: 'Get dressed',
          say: 'Now get dressed. What goes on first?',
          icon: FaTshirt,
          engine: 'sequence',
          lifeSkill: 'dressing',
          domains: ['sequencing', 'motorPlanning'],
          config: { trials: 1, mode: 'routine', layout: 'row', sequenceIds: ['gettingDressed'] },
        },
        {
          id: 'pack',
          title: 'Pack your bag',
          say: 'Pack what you need for school.',
          icon: GiSchoolBag,
          engine: 'collect',
          lifeSkill: 'school',
          domains: ['workingMemory', 'independence'],
          config: {
            trials: 1,
            task: 'need',
            mode: 'touch',
            sets: ['school', 'household', 'hygiene'],
            needCat: 'school',
            needPrompt: 'Pack what you need for school',
          },
        },
        {
          id: 'pay',
          title: 'Pay for lunch',
          say: 'You need coins for your lunch.',
          icon: FaMoneyBillWave,
          engine: 'collect',
          lifeSkill: 'money',
          domains: ['workingMemory', 'independence'],
          config: { trials: 1, task: 'money', mode: 'touch', sets: ['money'] },
        },
        {
          id: 'road',
          title: 'Cross the road',
          say: 'Time to cross the road. Green means walk, red means freeze.',
          icon: FaTrafficLight,
          engine: 'cue',
          lifeSkill: 'roadSafety',
          domains: ['inhibition', 'sustainedAttention'],
          config: { trials: 2, mode: 'lights', amber: true },
        },
        {
          id: 'classroom',
          title: 'Listen to the teacher',
          say: 'The teacher has three things for you to do.',
          icon: FaAppleWhole,
          engine: 'pose',
          lifeSkill: 'instructions',
          domains: ['workingMemory', 'auditoryComprehension'],
          config: { trials: 2, mode: 'instructions', touchSets: ['school', 'shapes'] },
        },
        {
          id: 'help',
          title: 'Ask for help',
          say: 'You cannot find your pencil. What can you do?',
          icon: FaHandsHelping,
          engine: 'tap',
          lifeSkill: 'help',
          domains: ['socialReasoning', 'independence'],
          config: {
            trials: 2,
            layout: 'row',
            captions: true,
            makeTrial: askScenario({ kinds: ['help'] }),
          },
        },
      ],
    },
  }),

  // ══════════════════════════════════════════════════════════════════════════
  // TALK & TOGETHER
  // ══════════════════════════════════════════════════════════════════════════
  g({
    id: 'follow-two',
    group: 'together',
    title: 'Follow Two Things',
    icon: FaListOl,
    color: 'blue',
    how: '"Touch the star, then clap your hands." Two things, in order.',
    engine: 'pose',
    dims: 'instruct',
    domains: ['auditoryComprehension', 'workingMemory', 'motorPlanning'],
    lifeSkill: 'instructions',
    featured: true,
    showBody: true,
    start: { steps: 2 },
    config: { trials: 8, mode: 'instructions', touchSets: ['shapes', 'colors'] },
  }),
  g({
    id: 'follow-three',
    group: 'together',
    title: 'Follow Three Things',
    icon: FaListCheck,
    color: 'purple',
    how: '"Touch the 3, clap, then touch the blue one." Three, in order.',
    engine: 'pose',
    dims: 'instruct',
    domains: ['auditoryComprehension', 'workingMemory', 'sequencing'],
    lifeSkill: 'instructions',
    showBody: true,
    start: { steps: 4 },
    config: { trials: 8, mode: 'instructions', touchSets: ['digits', 'colors', 'shapes'] },
  }),
  g({
    id: 'emotion-match',
    group: 'together',
    title: 'How Would They Feel?',
    icon: FaSmile,
    color: 'yellow',
    how: 'Something happens in the story. Which feeling fits?',
    engine: 'tap',
    dims: 'discriminate',
    domains: ['socialReasoning', 'auditoryComprehension'],
    lifeSkill: 'communication',
    featured: true,
    config: {
      trials: 10,
      layout: 'row',
      captions: true,
      makeTrial: askScenario({ kinds: ['emotion'] }),
    },
  }),
  g({
    id: 'what-should-i-do',
    group: 'together',
    title: 'What Should I Do?',
    icon: FaQuestion,
    color: 'teal',
    how: '"Someone dropped their pencil." What is the kind thing to do?',
    engine: 'tap',
    dims: 'discriminate',
    domains: ['socialReasoning', 'independence'],
    lifeSkill: 'socialPlay',
    featured: true,
    config: {
      trials: 10,
      layout: 'row',
      captions: true,
      makeTrial: askScenario({ kinds: ['social'] }),
    },
  }),
  g({
    id: 'ask-for-help',
    group: 'together',
    title: 'Ask For Help',
    icon: FaHandsHelping,
    color: 'green',
    how: 'The jar will not open. Choosing to ask is the answer.',
    engine: 'tap',
    dims: 'discriminate',
    domains: ['socialReasoning', 'independence', 'auditoryComprehension'],
    lifeSkill: 'help',
    config: {
      trials: 8,
      layout: 'row',
      captions: true,
      makeTrial: askScenario({ kinds: ['help'] }),
    },
  }),
  g({
    id: 'stay-safe-choices',
    group: 'together',
    title: 'Stop, Think, Do',
    icon: FaFireExtinguisher,
    color: 'red',
    how: 'Something has gone wrong. Stop, think, then choose what to do.',
    engine: 'tap',
    dims: 'discriminate',
    domains: ['socialReasoning', 'inhibition', 'independence'],
    lifeSkill: 'homeSafety',
    config: {
      trials: 8,
      layout: 'row',
      captions: true,
      promptHoldMs: 1600,
      makeTrial: askScenario({ kinds: ['safety'] }),
    },
  }),
  g({
    id: 'time-of-day',
    group: 'together',
    title: 'When Do We?',
    icon: FaClock,
    color: 'orange',
    how: 'Toothbrush — morning or night? Matching things to times of day.',
    engine: 'tap',
    dims: 'discriminate',
    domains: ['sequencing', 'auditoryComprehension'],
    lifeSkill: 'routines',
    config: { trials: 10, layout: 'row', captions: true, makeTrial: askTimeOfDay() },
  }),
  g({
    id: 'coin-names',
    group: 'together',
    title: 'Which Coin?',
    icon: FaCoins,
    color: 'yellow',
    how: '"Which one is fifty cent?" Naming and finding money.',
    engine: 'tap',
    dims: 'discriminate',
    domains: ['readingSymbol', 'auditoryComprehension'],
    lifeSkill: 'money',
    config: { trials: 10, spriteKind: 'text', makeTrial: askMoney({ maxCents: 200 }) },
  }),
]

export const GAME_BY_ID = Object.fromEntries(GAMES.map((x) => [x.id, x]))

export function gamesInGroup(groupId) {
  return GAMES.filter((x) => x.group === groupId)
}

export function featuredGames() {
  return GAMES.filter((x) => x.featured)
}

export function getGame(id) {
  return GAME_BY_ID[id] || null
}

/** Every game that trains a given functional domain. */
export function gamesForDomain(domain) {
  return GAMES.filter((x) => (x.domains || []).includes(domain))
}

/** Every game that transfers to a given life skill. */
export function gamesForLifeSkill(skill) {
  return GAMES.filter((x) => x.lifeSkill === skill)
}
