/**
 * Basics pack — the pre-academic foundation: shapes, colours, digits, dot
 * quantities, both letter cases and initial sounds.
 *
 * Consumed by the discrimination games ("touch the triangle", "touch the red
 * one"), the number-sense game (which pairs `digits` with `quantities` on
 * attrs.count) and the literacy games (which pair `phonics` with
 * `lettersUpper` / `lettersLower` on attrs.sound).
 *
 * Two data conventions carry real weight here, so they are deliberate:
 *
 * 1. `cats` are structural, not decorative. Every letter in a case set would
 *    otherwise share an identical category list, which pushes `similarity()`
 *    straight into the confusable band for *every* pair and flattens the
 *    difficulty ladder. So letters carry how they are drawn (curved,
 *    straight-lines, ascender, enclosed, diagonal…) — which is also exactly
 *    the dimension a visual-discrimination task is training.
 * 2. `attrs.sound` is the phoneme, not the letter, so that a phonics item
 *    matches object items in the other packs ('cat' → sound 'k'). The one
 *    consequence: C and K both carry sound 'k', so a game that resolves a
 *    /k/ prompt against `lettersUpper` must accept either letter. `phonics`
 *    itself only ships /k/ once (as C, by far the more useful first grapheme).
 *
 * Colour names outside core/draw.js's PALETTE ('brown', 'black') are safe:
 * colorOf() falls through to the raw CSS colour name.
 */

const shapes = [
  {
    id: 'shape-circle',
    label: 'Circle',
    shape: 'circle',
    cats: ['shape', 'curved', 'round', 'no-corners'],
    attrs: { color: 'red', size: 'big', sides: 0 },
    confusable: ['shape-oval'],
  },
  {
    id: 'shape-oval',
    label: 'Oval',
    shape: 'oval',
    cats: ['shape', 'curved', 'round', 'no-corners', 'stretched'],
    attrs: { color: 'orange', size: 'big', sides: 0 },
    confusable: ['shape-circle'],
  },
  {
    id: 'shape-square',
    label: 'Square',
    shape: 'square',
    cats: ['shape', 'polygon', 'quadrilateral', 'corners', 'equal-sides'],
    attrs: { color: 'blue', size: 'big', sides: 4 },
    confusable: ['shape-rectangle', 'shape-diamond'],
  },
  {
    id: 'shape-rectangle',
    label: 'Rectangle',
    shape: 'rectangle',
    cats: ['shape', 'polygon', 'quadrilateral', 'corners', 'stretched'],
    attrs: { color: 'teal', size: 'big', sides: 4 },
    confusable: ['shape-square'],
  },
  {
    id: 'shape-triangle',
    label: 'Triangle',
    shape: 'triangle',
    cats: ['shape', 'polygon', 'corners', 'pointed', 'three-sides'],
    attrs: { color: 'green', size: 'big', sides: 3 },
    confusable: ['shape-diamond', 'shape-arrow'],
  },
  {
    id: 'shape-diamond',
    label: 'Diamond',
    shape: 'diamond',
    cats: ['shape', 'polygon', 'quadrilateral', 'corners', 'pointed', 'tilted'],
    attrs: { color: 'purple', size: 'big', sides: 4 },
    confusable: ['shape-square', 'shape-triangle'],
  },
  {
    id: 'shape-star',
    label: 'Star',
    shape: 'star',
    cats: ['shape', 'polygon', 'pointed', 'symbol', 'many-corners'],
    attrs: { color: 'yellow', size: 'big', sides: 10 },
    // A five-pointed star and a pentagon share their five corners, which is
    // exactly why children name one for the other.
    confusable: ['shape-pentagon', 'shape-cross'],
  },
  {
    id: 'shape-pentagon',
    label: 'Pentagon',
    shape: 'pentagon',
    cats: ['shape', 'polygon', 'corners', 'equal-sides', 'many-sides'],
    attrs: { color: 'pink', size: 'big', sides: 5 },
    confusable: ['shape-hexagon'],
  },
  {
    id: 'shape-hexagon',
    label: 'Hexagon',
    shape: 'hexagon',
    cats: ['shape', 'polygon', 'corners', 'equal-sides', 'many-sides'],
    attrs: { color: 'teal', size: 'big', sides: 6 },
    confusable: ['shape-pentagon'],
  },
  {
    id: 'shape-heart',
    label: 'Heart',
    shape: 'heart',
    cats: ['shape', 'curved', 'symbol', 'pointed'],
    attrs: { color: 'pink', size: 'small', sides: 0 },
    // The playing-card confusion: wide on top, one point at the bottom.
    confusable: ['shape-diamond'],
  },
  {
    id: 'shape-cross',
    label: 'Cross',
    shape: 'cross',
    cats: ['shape', 'polygon', 'symbol', 'corners', 'straight-sides'],
    attrs: { color: 'red', size: 'small', sides: 12 },
    confusable: ['shape-star'],
  },
  {
    id: 'shape-arrow',
    label: 'Arrow',
    shape: 'arrow',
    cats: ['shape', 'polygon', 'symbol', 'pointed', 'corners'],
    attrs: { color: 'orange', size: 'small', sides: 7 },
    // An arrowhead *is* a triangle, so the two are named for each other.
    confusable: ['shape-triangle'],
  },
]

// A colour swatch is a plain circle whose fill comes from attrs.color, so the
// only thing that varies between these items is the thing being taught.
const colors = [
  {
    id: 'colour-red',
    label: 'Red',
    shape: 'circle',
    cats: ['colour', 'warm', 'primary', 'strong'],
    attrs: { color: 'red', initial: 'r' },
    confusable: ['colour-orange', 'colour-pink'],
  },
  {
    id: 'colour-blue',
    label: 'Blue',
    shape: 'circle',
    cats: ['colour', 'cool', 'primary', 'strong'],
    attrs: { color: 'blue', initial: 'b' },
    confusable: ['colour-green'],
  },
  {
    id: 'colour-green',
    label: 'Green',
    shape: 'circle',
    cats: ['colour', 'cool', 'secondary', 'nature'],
    attrs: { color: 'green', initial: 'g' },
    confusable: ['colour-blue'],
  },
  {
    id: 'colour-yellow',
    label: 'Yellow',
    shape: 'circle',
    cats: ['colour', 'warm', 'primary', 'bright'],
    attrs: { color: 'yellow', initial: 'y' },
    confusable: ['colour-orange'],
  },
  {
    id: 'colour-orange',
    label: 'Orange',
    shape: 'circle',
    cats: ['colour', 'warm', 'secondary', 'bright'],
    attrs: { color: 'orange', initial: 'o' },
    confusable: ['colour-red', 'colour-yellow', 'colour-brown'],
  },
  {
    id: 'colour-purple',
    label: 'Purple',
    shape: 'circle',
    cats: ['colour', 'cool', 'secondary', 'strong'],
    attrs: { color: 'purple', initial: 'p' },
    confusable: ['colour-pink'],
  },
  {
    id: 'colour-pink',
    label: 'Pink',
    shape: 'circle',
    cats: ['colour', 'warm', 'secondary', 'pale'],
    attrs: { color: 'pink', initial: 'p' },
    confusable: ['colour-red', 'colour-purple'],
  },
  {
    id: 'colour-brown',
    label: 'Brown',
    shape: 'circle',
    cats: ['colour', 'warm', 'earthy', 'dark'],
    attrs: { color: 'brown', initial: 'b' },
    confusable: ['colour-black', 'colour-orange'],
  },
  {
    id: 'colour-black',
    label: 'Black',
    shape: 'circle',
    cats: ['colour', 'neutral', 'dark'],
    attrs: { color: 'black', initial: 'b' },
    confusable: ['colour-brown'],
  },
  {
    id: 'colour-white',
    label: 'White',
    shape: 'circle',
    cats: ['colour', 'neutral', 'pale'],
    attrs: { color: 'white', initial: 'w' },
  },
]

// attrs.count is the join key with `quantities` — keep the two sets in step.
const digits = [
  {
    id: 'digit-0',
    label: 'Zero',
    text: '0',
    cats: ['number', 'digit', 'numeral', 'even', 'zero', 'small-number'],
    attrs: { count: 0, initial: 'z', amount: 'few' },
    confusable: ['digit-8'],
  },
  {
    id: 'digit-1',
    label: 'One',
    text: '1',
    cats: ['number', 'digit', 'numeral', 'odd', 'small-number'],
    attrs: { count: 1, initial: 'o', amount: 'few' },
    confusable: ['digit-7'],
  },
  {
    id: 'digit-2',
    label: 'Two',
    text: '2',
    cats: ['number', 'digit', 'numeral', 'even', 'small-number'],
    attrs: { count: 2, initial: 't', amount: 'few' },
    confusable: ['digit-5'],
  },
  {
    id: 'digit-3',
    label: 'Three',
    text: '3',
    cats: ['number', 'digit', 'numeral', 'odd', 'small-number'],
    attrs: { count: 3, initial: 't', amount: 'few' },
    confusable: ['digit-8'],
  },
  {
    id: 'digit-4',
    label: 'Four',
    text: '4',
    cats: ['number', 'digit', 'numeral', 'even', 'middle-number'],
    attrs: { count: 4, initial: 'f', amount: 'some' },
  },
  {
    id: 'digit-5',
    label: 'Five',
    text: '5',
    cats: ['number', 'digit', 'numeral', 'odd', 'middle-number'],
    attrs: { count: 5, initial: 'f', amount: 'some' },
    confusable: ['digit-2'],
  },
  {
    id: 'digit-6',
    label: 'Six',
    text: '6',
    cats: ['number', 'digit', 'numeral', 'even', 'middle-number'],
    attrs: { count: 6, initial: 's', amount: 'some' },
    confusable: ['digit-9'],
  },
  {
    id: 'digit-7',
    label: 'Seven',
    text: '7',
    cats: ['number', 'digit', 'numeral', 'odd', 'big-number'],
    attrs: { count: 7, initial: 's', amount: 'many' },
    confusable: ['digit-1'],
  },
  {
    id: 'digit-8',
    label: 'Eight',
    text: '8',
    cats: ['number', 'digit', 'numeral', 'even', 'big-number'],
    attrs: { count: 8, initial: 'e', amount: 'many' },
    confusable: ['digit-3', 'digit-0'],
  },
  {
    id: 'digit-9',
    label: 'Nine',
    text: '9',
    cats: ['number', 'digit', 'numeral', 'odd', 'big-number'],
    attrs: { count: 9, initial: 'n', amount: 'many' },
    confusable: ['digit-6'],
  },
]

// Dot clusters. `confusable` is neighbour-by-one from 3 upwards: past the
// subitising limit a child miscounts by one, which is the real error to train.
const quantities = [
  {
    id: 'qty-1',
    label: 'One dot',
    quantity: 1,
    cats: ['number', 'quantity', 'dots', 'odd', 'few'],
    attrs: { count: 1, initial: 'o', amount: 'few' },
  },
  {
    id: 'qty-2',
    label: 'Two dots',
    quantity: 2,
    cats: ['number', 'quantity', 'dots', 'even', 'few'],
    attrs: { count: 2, initial: 't', amount: 'few' },
    confusable: ['qty-3'],
  },
  {
    id: 'qty-3',
    label: 'Three dots',
    quantity: 3,
    cats: ['number', 'quantity', 'dots', 'odd', 'few'],
    attrs: { count: 3, initial: 't', amount: 'few' },
    confusable: ['qty-2', 'qty-4'],
  },
  {
    id: 'qty-4',
    label: 'Four dots',
    quantity: 4,
    cats: ['number', 'quantity', 'dots', 'even', 'some'],
    attrs: { count: 4, initial: 'f', amount: 'some' },
    confusable: ['qty-3', 'qty-5'],
  },
  {
    id: 'qty-5',
    label: 'Five dots',
    quantity: 5,
    cats: ['number', 'quantity', 'dots', 'odd', 'some'],
    attrs: { count: 5, initial: 'f', amount: 'some' },
    confusable: ['qty-4', 'qty-6'],
  },
  {
    id: 'qty-6',
    label: 'Six dots',
    quantity: 6,
    cats: ['number', 'quantity', 'dots', 'even', 'some'],
    attrs: { count: 6, initial: 's', amount: 'some' },
    confusable: ['qty-5', 'qty-7'],
  },
  {
    id: 'qty-7',
    label: 'Seven dots',
    quantity: 7,
    cats: ['number', 'quantity', 'dots', 'odd', 'many'],
    attrs: { count: 7, initial: 's', amount: 'many' },
    confusable: ['qty-6', 'qty-8'],
  },
  {
    id: 'qty-8',
    label: 'Eight dots',
    quantity: 8,
    cats: ['number', 'quantity', 'dots', 'even', 'many'],
    attrs: { count: 8, initial: 'e', amount: 'many' },
    confusable: ['qty-7', 'qty-9'],
  },
  {
    id: 'qty-9',
    label: 'Nine dots',
    quantity: 9,
    cats: ['number', 'quantity', 'dots', 'odd', 'many'],
    attrs: { count: 9, initial: 'n', amount: 'many' },
    confusable: ['qty-8', 'qty-10'],
  },
  {
    id: 'qty-10',
    label: 'Ten dots',
    quantity: 10,
    cats: ['number', 'quantity', 'dots', 'even', 'many'],
    attrs: { count: 10, initial: 't', amount: 'many' },
    confusable: ['qty-9'],
  },
]

// `speak` says "capital A" / "small a" because speech synthesis cannot voice
// the difference between the two cases, and case is the whole point here.
const lettersUpper = [
  {
    id: 'upper-a',
    label: 'A',
    text: 'A',
    speak: 'capital A',
    cats: ['letter', 'uppercase', 'vowel', 'straight-lines', 'pointed', 'symmetric'],
    attrs: { initial: 'a', sound: 'a', case: 'upper' },
    // A is a V with a bar; the rotation confusion is well documented.
    confusable: ['upper-v'],
  },
  {
    id: 'upper-b',
    label: 'B',
    text: 'B',
    speak: 'capital B',
    cats: ['letter', 'uppercase', 'consonant', 'mixed-lines', 'enclosed', 'round-parts'],
    attrs: { initial: 'b', sound: 'b', case: 'upper' },
    confusable: ['upper-d', 'upper-p', 'upper-q'],
  },
  {
    id: 'upper-c',
    label: 'C',
    text: 'C',
    speak: 'capital C',
    cats: ['letter', 'uppercase', 'consonant', 'curved', 'open', 'round-parts'],
    attrs: { initial: 'c', sound: 'k', case: 'upper' },
    confusable: ['upper-g'],
  },
  {
    id: 'upper-d',
    label: 'D',
    text: 'D',
    speak: 'capital D',
    cats: ['letter', 'uppercase', 'consonant', 'mixed-lines', 'enclosed', 'round-parts'],
    attrs: { initial: 'd', sound: 'd', case: 'upper' },
    confusable: ['upper-b', 'upper-p', 'upper-q'],
  },
  {
    id: 'upper-e',
    label: 'E',
    text: 'E',
    speak: 'capital E',
    cats: ['letter', 'uppercase', 'vowel', 'straight-lines', 'open', 'bars'],
    attrs: { initial: 'e', sound: 'e', case: 'upper' },
    confusable: ['upper-f'],
  },
  {
    id: 'upper-f',
    label: 'F',
    text: 'F',
    speak: 'capital F',
    cats: ['letter', 'uppercase', 'consonant', 'straight-lines', 'open', 'bars'],
    attrs: { initial: 'f', sound: 'f', case: 'upper' },
    confusable: ['upper-e'],
  },
  {
    id: 'upper-g',
    label: 'G',
    text: 'G',
    speak: 'capital G',
    cats: ['letter', 'uppercase', 'consonant', 'curved', 'open', 'round-parts', 'bars'],
    attrs: { initial: 'g', sound: 'g', case: 'upper' },
    confusable: ['upper-c'],
  },
  {
    id: 'upper-h',
    label: 'H',
    text: 'H',
    speak: 'capital H',
    cats: ['letter', 'uppercase', 'consonant', 'straight-lines', 'bars', 'symmetric'],
    attrs: { initial: 'h', sound: 'h', case: 'upper' },
  },
  {
    id: 'upper-i',
    label: 'I',
    text: 'I',
    speak: 'capital I',
    cats: ['letter', 'uppercase', 'vowel', 'straight-lines', 'bars', 'symmetric', 'narrow'],
    attrs: { initial: 'i', sound: 'i', case: 'upper' },
    confusable: ['upper-l', 'upper-t'],
  },
  {
    id: 'upper-j',
    label: 'J',
    text: 'J',
    speak: 'capital J',
    cats: ['letter', 'uppercase', 'consonant', 'curved', 'open', 'hook'],
    attrs: { initial: 'j', sound: 'j', case: 'upper' },
  },
  {
    id: 'upper-k',
    label: 'K',
    text: 'K',
    speak: 'capital K',
    cats: ['letter', 'uppercase', 'consonant', 'straight-lines', 'pointed', 'diagonal'],
    attrs: { initial: 'k', sound: 'k', case: 'upper' },
    confusable: ['upper-x'],
  },
  {
    id: 'upper-l',
    label: 'L',
    text: 'L',
    speak: 'capital L',
    cats: ['letter', 'uppercase', 'consonant', 'straight-lines', 'open', 'corner'],
    attrs: { initial: 'l', sound: 'l', case: 'upper' },
    confusable: ['upper-i', 'upper-t'],
  },
  {
    id: 'upper-m',
    label: 'M',
    text: 'M',
    speak: 'capital M',
    cats: ['letter', 'uppercase', 'consonant', 'straight-lines', 'pointed', 'symmetric', 'diagonal', 'wide'],
    attrs: { initial: 'm', sound: 'm', case: 'upper' },
    confusable: ['upper-w'],
  },
  {
    id: 'upper-n',
    label: 'N',
    text: 'N',
    speak: 'capital N',
    cats: ['letter', 'uppercase', 'consonant', 'straight-lines', 'diagonal'],
    attrs: { initial: 'n', sound: 'n', case: 'upper' },
    confusable: ['upper-u'],
  },
  {
    id: 'upper-o',
    label: 'O',
    text: 'O',
    speak: 'capital O',
    cats: ['letter', 'uppercase', 'vowel', 'curved', 'enclosed', 'round-parts', 'symmetric'],
    attrs: { initial: 'o', sound: 'o', case: 'upper' },
    confusable: ['upper-q'],
  },
  {
    id: 'upper-p',
    label: 'P',
    text: 'P',
    speak: 'capital P',
    cats: ['letter', 'uppercase', 'consonant', 'mixed-lines', 'enclosed', 'round-parts'],
    attrs: { initial: 'p', sound: 'p', case: 'upper' },
    confusable: ['upper-b', 'upper-d', 'upper-q'],
  },
  {
    id: 'upper-q',
    label: 'Q',
    text: 'Q',
    speak: 'capital Q',
    cats: ['letter', 'uppercase', 'consonant', 'curved', 'enclosed', 'round-parts', 'tail'],
    attrs: { initial: 'q', sound: 'kw', case: 'upper' },
    confusable: ['upper-o', 'upper-b', 'upper-d', 'upper-p'],
  },
  {
    id: 'upper-r',
    label: 'R',
    text: 'R',
    speak: 'capital R',
    cats: ['letter', 'uppercase', 'consonant', 'mixed-lines', 'enclosed', 'round-parts', 'diagonal'],
    attrs: { initial: 'r', sound: 'r', case: 'upper' },
  },
  {
    id: 'upper-s',
    label: 'S',
    text: 'S',
    speak: 'capital S',
    cats: ['letter', 'uppercase', 'consonant', 'curved', 'open', 'wavy'],
    attrs: { initial: 's', sound: 's', case: 'upper' },
    confusable: ['upper-z'],
  },
  {
    id: 'upper-t',
    label: 'T',
    text: 'T',
    speak: 'capital T',
    cats: ['letter', 'uppercase', 'consonant', 'straight-lines', 'bars', 'symmetric'],
    attrs: { initial: 't', sound: 't', case: 'upper' },
    confusable: ['upper-i', 'upper-l'],
  },
  {
    id: 'upper-u',
    label: 'U',
    text: 'U',
    speak: 'capital U',
    cats: ['letter', 'uppercase', 'vowel', 'curved', 'open', 'symmetric'],
    attrs: { initial: 'u', sound: 'u', case: 'upper' },
    confusable: ['upper-n'],
  },
  {
    id: 'upper-v',
    label: 'V',
    text: 'V',
    speak: 'capital V',
    cats: ['letter', 'uppercase', 'consonant', 'straight-lines', 'pointed', 'symmetric', 'diagonal', 'narrow'],
    attrs: { initial: 'v', sound: 'v', case: 'upper' },
    confusable: ['upper-y'],
  },
  {
    id: 'upper-w',
    label: 'W',
    text: 'W',
    speak: 'capital W',
    cats: ['letter', 'uppercase', 'consonant', 'straight-lines', 'pointed', 'symmetric', 'diagonal', 'wide'],
    attrs: { initial: 'w', sound: 'w', case: 'upper' },
    confusable: ['upper-m'],
  },
  {
    id: 'upper-x',
    label: 'X',
    text: 'X',
    speak: 'capital X',
    cats: ['letter', 'uppercase', 'consonant', 'straight-lines', 'pointed', 'symmetric', 'diagonal', 'crossed'],
    attrs: { initial: 'x', sound: 'ks', case: 'upper' },
    confusable: ['upper-k'],
  },
  {
    id: 'upper-y',
    label: 'Y',
    text: 'Y',
    speak: 'capital Y',
    cats: ['letter', 'uppercase', 'consonant', 'straight-lines', 'pointed', 'symmetric', 'diagonal', 'stem'],
    attrs: { initial: 'y', sound: 'y', case: 'upper' },
    confusable: ['upper-v'],
  },
  {
    id: 'upper-z',
    label: 'Z',
    text: 'Z',
    speak: 'capital Z',
    cats: ['letter', 'uppercase', 'consonant', 'straight-lines', 'pointed', 'diagonal', 'bars'],
    attrs: { initial: 'z', sound: 'z', case: 'upper' },
    confusable: ['upper-s'],
  },
]

// Lower case carries the letter-reversal confusions that matter most in
// dyslexia support, so ascender/descender/round-body are first-class cats.
const lettersLower = [
  {
    id: 'lower-a',
    label: 'a',
    text: 'a',
    speak: 'small a',
    cats: ['letter', 'lowercase', 'vowel', 'x-height', 'round-body', 'curved'],
    attrs: { initial: 'a', sound: 'a', case: 'lower' },
    confusable: ['lower-o', 'lower-e'],
  },
  {
    id: 'lower-b',
    label: 'b',
    text: 'b',
    speak: 'small b',
    cats: ['letter', 'lowercase', 'consonant', 'ascender', 'round-body', 'mixed-lines'],
    attrs: { initial: 'b', sound: 'b', case: 'lower' },
    confusable: ['lower-d', 'lower-p', 'lower-q', 'lower-g'],
  },
  {
    id: 'lower-c',
    label: 'c',
    text: 'c',
    speak: 'small c',
    cats: ['letter', 'lowercase', 'consonant', 'x-height', 'curved', 'open'],
    attrs: { initial: 'c', sound: 'k', case: 'lower' },
    confusable: ['lower-e', 'lower-o'],
  },
  {
    id: 'lower-d',
    label: 'd',
    text: 'd',
    speak: 'small d',
    cats: ['letter', 'lowercase', 'consonant', 'ascender', 'round-body', 'mixed-lines'],
    attrs: { initial: 'd', sound: 'd', case: 'lower' },
    confusable: ['lower-b', 'lower-p', 'lower-q', 'lower-g'],
  },
  {
    id: 'lower-e',
    label: 'e',
    text: 'e',
    speak: 'small e',
    cats: ['letter', 'lowercase', 'vowel', 'x-height', 'curved', 'round-body', 'bar'],
    attrs: { initial: 'e', sound: 'e', case: 'lower' },
    confusable: ['lower-a', 'lower-c', 'lower-o'],
  },
  {
    id: 'lower-f',
    label: 'f',
    text: 'f',
    speak: 'small f',
    cats: ['letter', 'lowercase', 'consonant', 'ascender', 'curved', 'bar'],
    attrs: { initial: 'f', sound: 'f', case: 'lower' },
    confusable: ['lower-t'],
  },
  {
    id: 'lower-g',
    label: 'g',
    text: 'g',
    speak: 'small g',
    cats: ['letter', 'lowercase', 'consonant', 'descender', 'round-body', 'curved'],
    attrs: { initial: 'g', sound: 'g', case: 'lower' },
    confusable: ['lower-b', 'lower-d', 'lower-p', 'lower-q'],
  },
  {
    id: 'lower-h',
    label: 'h',
    text: 'h',
    speak: 'small h',
    cats: ['letter', 'lowercase', 'consonant', 'ascender', 'arch', 'straight-lines'],
    attrs: { initial: 'h', sound: 'h', case: 'lower' },
    confusable: ['lower-n', 'lower-b'],
  },
  {
    id: 'lower-i',
    label: 'i',
    text: 'i',
    speak: 'small i',
    cats: ['letter', 'lowercase', 'vowel', 'x-height', 'dotted', 'narrow', 'straight-lines'],
    attrs: { initial: 'i', sound: 'i', case: 'lower' },
    confusable: ['lower-j', 'lower-l'],
  },
  {
    id: 'lower-j',
    label: 'j',
    text: 'j',
    speak: 'small j',
    cats: ['letter', 'lowercase', 'consonant', 'descender', 'dotted', 'hook', 'narrow'],
    attrs: { initial: 'j', sound: 'j', case: 'lower' },
    confusable: ['lower-i', 'lower-g'],
  },
  {
    id: 'lower-k',
    label: 'k',
    text: 'k',
    speak: 'small k',
    cats: ['letter', 'lowercase', 'consonant', 'ascender', 'straight-lines', 'diagonal'],
    attrs: { initial: 'k', sound: 'k', case: 'lower' },
    confusable: ['lower-x'],
  },
  {
    id: 'lower-l',
    label: 'l',
    text: 'l',
    speak: 'small l',
    cats: ['letter', 'lowercase', 'consonant', 'ascender', 'narrow', 'straight-lines'],
    attrs: { initial: 'l', sound: 'l', case: 'lower' },
    confusable: ['lower-i', 'lower-j', 'lower-t'],
  },
  {
    id: 'lower-m',
    label: 'm',
    text: 'm',
    speak: 'small m',
    cats: ['letter', 'lowercase', 'consonant', 'x-height', 'arch', 'wide', 'straight-lines'],
    attrs: { initial: 'm', sound: 'm', case: 'lower' },
    confusable: ['lower-n', 'lower-w', 'lower-u'],
  },
  {
    id: 'lower-n',
    label: 'n',
    text: 'n',
    speak: 'small n',
    cats: ['letter', 'lowercase', 'consonant', 'x-height', 'arch', 'straight-lines'],
    attrs: { initial: 'n', sound: 'n', case: 'lower' },
    confusable: ['lower-m', 'lower-u', 'lower-h', 'lower-r', 'lower-w'],
  },
  {
    id: 'lower-o',
    label: 'o',
    text: 'o',
    speak: 'small o',
    cats: ['letter', 'lowercase', 'vowel', 'x-height', 'round-body', 'curved', 'enclosed'],
    attrs: { initial: 'o', sound: 'o', case: 'lower' },
    confusable: ['lower-a', 'lower-e', 'lower-c'],
  },
  {
    id: 'lower-p',
    label: 'p',
    text: 'p',
    speak: 'small p',
    cats: ['letter', 'lowercase', 'consonant', 'descender', 'round-body', 'mixed-lines'],
    attrs: { initial: 'p', sound: 'p', case: 'lower' },
    confusable: ['lower-b', 'lower-d', 'lower-q', 'lower-g'],
  },
  {
    id: 'lower-q',
    label: 'q',
    text: 'q',
    speak: 'small q',
    cats: ['letter', 'lowercase', 'consonant', 'descender', 'round-body', 'mixed-lines'],
    attrs: { initial: 'q', sound: 'kw', case: 'lower' },
    confusable: ['lower-b', 'lower-d', 'lower-p', 'lower-g'],
  },
  {
    id: 'lower-r',
    label: 'r',
    text: 'r',
    speak: 'small r',
    cats: ['letter', 'lowercase', 'consonant', 'x-height', 'arch', 'straight-lines', 'open'],
    attrs: { initial: 'r', sound: 'r', case: 'lower' },
    confusable: ['lower-n'],
  },
  {
    id: 'lower-s',
    label: 's',
    text: 's',
    speak: 'small s',
    cats: ['letter', 'lowercase', 'consonant', 'x-height', 'curved', 'wavy'],
    attrs: { initial: 's', sound: 's', case: 'lower' },
    confusable: ['lower-z'],
  },
  {
    id: 'lower-t',
    label: 't',
    text: 't',
    speak: 'small t',
    cats: ['letter', 'lowercase', 'consonant', 'ascender', 'bar', 'straight-lines'],
    attrs: { initial: 't', sound: 't', case: 'lower' },
    confusable: ['lower-f', 'lower-l'],
  },
  {
    id: 'lower-u',
    label: 'u',
    text: 'u',
    speak: 'small u',
    cats: ['letter', 'lowercase', 'vowel', 'x-height', 'curved', 'open', 'symmetric'],
    attrs: { initial: 'u', sound: 'u', case: 'lower' },
    confusable: ['lower-n', 'lower-m', 'lower-w', 'lower-v'],
  },
  {
    id: 'lower-v',
    label: 'v',
    text: 'v',
    speak: 'small v',
    cats: ['letter', 'lowercase', 'consonant', 'x-height', 'pointed', 'diagonal', 'narrow'],
    attrs: { initial: 'v', sound: 'v', case: 'lower' },
    confusable: ['lower-u', 'lower-y'],
  },
  {
    id: 'lower-w',
    label: 'w',
    text: 'w',
    speak: 'small w',
    cats: ['letter', 'lowercase', 'consonant', 'x-height', 'pointed', 'diagonal', 'wide'],
    attrs: { initial: 'w', sound: 'w', case: 'lower' },
    confusable: ['lower-m', 'lower-u', 'lower-v'],
  },
  {
    id: 'lower-x',
    label: 'x',
    text: 'x',
    speak: 'small x',
    cats: ['letter', 'lowercase', 'consonant', 'x-height', 'pointed', 'diagonal', 'crossed'],
    attrs: { initial: 'x', sound: 'ks', case: 'lower' },
    confusable: ['lower-k'],
  },
  {
    id: 'lower-y',
    label: 'y',
    text: 'y',
    speak: 'small y',
    cats: ['letter', 'lowercase', 'consonant', 'descender', 'pointed', 'diagonal'],
    attrs: { initial: 'y', sound: 'y', case: 'lower' },
    confusable: ['lower-v', 'lower-g'],
  },
  {
    id: 'lower-z',
    label: 'z',
    text: 'z',
    speak: 'small z',
    cats: ['letter', 'lowercase', 'consonant', 'x-height', 'pointed', 'diagonal', 'bar'],
    attrs: { initial: 'z', sound: 'z', case: 'lower' },
    confusable: ['lower-s'],
  },
]

// The 20 highest-utility first sounds: five short vowels plus fifteen
// consonants. K, Q, V, X, Y and Z are left out on purpose — /k/ is taught here
// as C (cat, cup, car), and the rest are rare in a child's first words.
// `speak` spells the phoneme the way core/tts.js's speakPhoneme map does, so
// a plain speak() call and a phoneme call sound like the same teacher.
// Mouth-placement cats ('lips', 'tongue-tip'…) double as speech-therapy cues.
const phonics = [
  {
    id: 'phon-a',
    label: 'A says /a/',
    text: 'A',
    speak: 'A says ah',
    cats: ['phonics', 'letter-sound', 'vowel-sound', 'short-vowel', 'open-mouth'],
    attrs: { sound: 'a', initial: 'a', voice: 'voiced' },
    examples: ['apple', 'ant', 'arrow'],
    confusable: ['phon-u', 'phon-e'],
  },
  {
    id: 'phon-b',
    label: 'B says /b/',
    text: 'B',
    speak: 'B says buh',
    cats: ['phonics', 'letter-sound', 'consonant-sound', 'stop', 'lips'],
    attrs: { sound: 'b', initial: 'b', voice: 'voiced' },
    examples: ['ball', 'bus', 'bed'],
    confusable: ['phon-d', 'phon-p'],
  },
  {
    id: 'phon-c',
    label: 'C says /k/',
    text: 'C',
    speak: 'C says kuh',
    cats: ['phonics', 'letter-sound', 'consonant-sound', 'stop', 'back-of-mouth'],
    attrs: { sound: 'k', initial: 'c', voice: 'voiceless' },
    examples: ['cat', 'cup', 'car'],
    confusable: ['phon-g'],
  },
  {
    id: 'phon-d',
    label: 'D says /d/',
    text: 'D',
    speak: 'D says duh',
    cats: ['phonics', 'letter-sound', 'consonant-sound', 'stop', 'tongue-tip'],
    attrs: { sound: 'd', initial: 'd', voice: 'voiced' },
    examples: ['dog', 'doll', 'door'],
    confusable: ['phon-b', 'phon-t'],
  },
  {
    id: 'phon-e',
    label: 'E says /e/',
    text: 'E',
    speak: 'E says eh',
    cats: ['phonics', 'letter-sound', 'vowel-sound', 'short-vowel', 'open-mouth'],
    attrs: { sound: 'e', initial: 'e', voice: 'voiced' },
    examples: ['egg', 'elephant', 'engine'],
    confusable: ['phon-i', 'phon-a'],
  },
  {
    id: 'phon-f',
    label: 'F says /f/',
    text: 'F',
    speak: 'F says ff',
    cats: ['phonics', 'letter-sound', 'consonant-sound', 'fricative', 'teeth-and-lip'],
    attrs: { sound: 'f', initial: 'f', voice: 'voiceless' },
    examples: ['fish', 'fan', 'farm'],
    confusable: ['phon-s'],
  },
  {
    id: 'phon-g',
    label: 'G says /g/',
    text: 'G',
    speak: 'G says guh',
    cats: ['phonics', 'letter-sound', 'consonant-sound', 'stop', 'back-of-mouth'],
    attrs: { sound: 'g', initial: 'g', voice: 'voiced' },
    examples: ['goat', 'gate', 'garden'],
    confusable: ['phon-c', 'phon-j'],
  },
  {
    id: 'phon-h',
    label: 'H says /h/',
    text: 'H',
    speak: 'H says hh',
    cats: ['phonics', 'letter-sound', 'consonant-sound', 'fricative', 'breath'],
    attrs: { sound: 'h', initial: 'h', voice: 'voiceless' },
    examples: ['hat', 'house', 'hand'],
    // "hat" / "what": the h/wh pair is the live confusion in Irish English.
    confusable: ['phon-w'],
  },
  {
    id: 'phon-i',
    label: 'I says /i/',
    text: 'I',
    speak: 'I says ih',
    cats: ['phonics', 'letter-sound', 'vowel-sound', 'short-vowel', 'open-mouth'],
    attrs: { sound: 'i', initial: 'i', voice: 'voiced' },
    examples: ['insect', 'igloo', 'ink'],
    confusable: ['phon-e'],
  },
  {
    id: 'phon-j',
    label: 'J says /j/',
    text: 'J',
    speak: 'J says juh',
    cats: ['phonics', 'letter-sound', 'consonant-sound', 'affricate', 'tongue-body'],
    attrs: { sound: 'j', initial: 'j', voice: 'voiced' },
    examples: ['jam', 'jug', 'jelly'],
    confusable: ['phon-g'],
  },
  {
    id: 'phon-l',
    label: 'L says /l/',
    text: 'L',
    speak: 'L says ll',
    cats: ['phonics', 'letter-sound', 'consonant-sound', 'liquid', 'tongue-tip'],
    attrs: { sound: 'l', initial: 'l', voice: 'voiced' },
    examples: ['leg', 'lamp', 'lion'],
    confusable: ['phon-r'],
  },
  {
    id: 'phon-m',
    label: 'M says /m/',
    text: 'M',
    speak: 'M says mm',
    cats: ['phonics', 'letter-sound', 'consonant-sound', 'nasal', 'lips'],
    attrs: { sound: 'm', initial: 'm', voice: 'voiced' },
    examples: ['moon', 'milk', 'mouse'],
    confusable: ['phon-n'],
  },
  {
    id: 'phon-n',
    label: 'N says /n/',
    text: 'N',
    speak: 'N says nn',
    cats: ['phonics', 'letter-sound', 'consonant-sound', 'nasal', 'tongue-tip'],
    attrs: { sound: 'n', initial: 'n', voice: 'voiced' },
    examples: ['nose', 'nest', 'net'],
    confusable: ['phon-m'],
  },
  {
    id: 'phon-o',
    label: 'O says /o/',
    text: 'O',
    speak: 'O says oh',
    cats: ['phonics', 'letter-sound', 'vowel-sound', 'short-vowel', 'open-mouth'],
    attrs: { sound: 'o', initial: 'o', voice: 'voiced' },
    examples: ['orange', 'otter', 'octopus'],
    confusable: ['phon-u'],
  },
  {
    id: 'phon-p',
    label: 'P says /p/',
    text: 'P',
    speak: 'P says puh',
    cats: ['phonics', 'letter-sound', 'consonant-sound', 'stop', 'lips'],
    attrs: { sound: 'p', initial: 'p', voice: 'voiceless' },
    examples: ['pig', 'pen', 'park'],
    confusable: ['phon-b'],
  },
  {
    id: 'phon-r',
    label: 'R says /r/',
    text: 'R',
    speak: 'R says rr',
    cats: ['phonics', 'letter-sound', 'consonant-sound', 'liquid', 'tongue-body'],
    attrs: { sound: 'r', initial: 'r', voice: 'voiced' },
    examples: ['rain', 'rabbit', 'ring'],
    confusable: ['phon-l', 'phon-w'],
  },
  {
    id: 'phon-s',
    label: 'S says /s/',
    text: 'S',
    speak: 'S says sss',
    cats: ['phonics', 'letter-sound', 'consonant-sound', 'fricative', 'tongue-tip'],
    attrs: { sound: 's', initial: 's', voice: 'voiceless' },
    examples: ['sun', 'sock', 'snake'],
    confusable: ['phon-f'],
  },
  {
    id: 'phon-t',
    label: 'T says /t/',
    text: 'T',
    speak: 'T says tuh',
    cats: ['phonics', 'letter-sound', 'consonant-sound', 'stop', 'tongue-tip'],
    attrs: { sound: 't', initial: 't', voice: 'voiceless' },
    examples: ['tap', 'tent', 'table'],
    confusable: ['phon-d'],
  },
  {
    id: 'phon-u',
    label: 'U says /u/',
    text: 'U',
    speak: 'U says uh',
    cats: ['phonics', 'letter-sound', 'vowel-sound', 'short-vowel', 'open-mouth'],
    attrs: { sound: 'u', initial: 'u', voice: 'voiced' },
    examples: ['umbrella', 'up', 'under'],
    confusable: ['phon-o', 'phon-a'],
  },
  {
    id: 'phon-w',
    label: 'W says /w/',
    text: 'W',
    speak: 'W says wuh',
    cats: ['phonics', 'letter-sound', 'consonant-sound', 'glide', 'lips'],
    attrs: { sound: 'w', initial: 'w', voice: 'voiced' },
    examples: ['window', 'water', 'worm'],
    confusable: ['phon-r'],
  },
]

/** name -> Array<Item>. See ar/content/index.js for the item shape. */
export const SETS = {
  shapes,
  colors,
  digits,
  quantities,
  lettersUpper,
  lettersLower,
  phonics,
}
